import type { MockApiPayload } from './types';

export const mockData: MockApiPayload = {
  currentUser: {
    name: 'Chris Admin',
    role: 'CENTRAL_ADMIN',
    initials: 'CA',
  },
  depots: [
    {
      id: 'depot-1',
      name: 'London Central',
      location: 'Vauxhall, London',
      routesCount: 6,
      vehiclesCount: 8,
      driversCount: 12,
      status: 'Active',
    },
    {
      id: 'depot-2',
      name: 'Manchester North',
      location: 'Salford, Manchester',
      routesCount: 4,
      vehiclesCount: 5,
      driversCount: 8,
      status: 'Active',
    },
    {
      id: 'depot-3',
      name: 'Birmingham West',
      location: 'Handsworth, Birmingham',
      routesCount: 5,
      vehiclesCount: 6,
      driversCount: 9,
      status: 'Active',
    },
    {
      id: 'depot-4',
      name: 'Leeds Central',
      location: 'Holbeck, Leeds',
      routesCount: 3,
      vehiclesCount: 4,
      driversCount: 6,
      status: 'Active',
    },
    {
      id: 'depot-5',
      name: 'Bristol South',
      location: 'Bedminster, Bristol',
      routesCount: 3,
      vehiclesCount: 3,
      driversCount: 5,
      status: 'Config Review',
    },
  ],
  routes: [
    {
      id: 'route-a',
      depotId: 'depot-1',
      code: 'ROUTE-A',
      name: 'Route A — South West',
      coverage: 'SW1–SW20',
      postcodeRulesCount: 42,
      status: 'Active',
    },
    {
      id: 'route-b',
      depotId: 'depot-1',
      code: 'ROUTE-B',
      name: 'Route B — South East',
      coverage: 'SE1–SE25',
      postcodeRulesCount: 38,
      status: 'Active',
    },
    {
      id: 'route-c',
      depotId: 'depot-1',
      code: 'ROUTE-C',
      name: 'Route C — City',
      coverage: 'EC1–EC4',
      postcodeRulesCount: 28,
      status: 'Active',
    },
    {
      id: 'route-d',
      depotId: 'depot-1',
      code: 'ROUTE-D',
      name: 'Route D — West End',
      coverage: 'W1–W14, WC1–WC2',
      postcodeRulesCount: 51,
      status: 'Active',
    },
    {
      id: 'route-e',
      depotId: 'depot-1',
      code: 'ROUTE-E',
      name: 'Route E — North',
      coverage: 'N1–N22',
      postcodeRulesCount: 35,
      status: 'Active',
    },
    {
      id: 'route-f',
      depotId: 'depot-1',
      code: 'ROUTE-F',
      name: 'Route F — East',
      coverage: 'E1–E18',
      postcodeRulesCount: 44,
      status: 'Active',
    },
  ],
  dashboard: {
    date: '2026-03-12',
    summary: {
      totalRoutes: 6,
      deliveriesComplete: 142,
      deliveriesTotal: 231,
      boxesDelivered: 687,
      boxesTotal: 1104,
      exceptionsCount: 8,
    },
    routeSummary: [
      {
        routeId: 'route-a',
        routeName: 'Route A',
        description: 'SW zones',
        vehicle: 'LK71 ABC',
        driver: 'J. Patel',
        deliveriesDone: 42,
        deliveriesTotal: 42,
        boxesDone: 201,
        boxesTotal: 201,
        status: 'Complete',
      },
      {
        routeId: 'route-b',
        routeName: 'Route B',
        description: 'SE zones',
        vehicle: 'MN20 XYZ',
        driver: 'R. Ahmed',
        deliveriesDone: 31,
        deliveriesTotal: 48,
        boxesDone: 148,
        boxesTotal: 230,
        status: 'In Progress',
      },
      {
        routeId: 'route-c',
        routeName: 'Route C',
        description: 'EC zones',
        vehicle: 'PQ19 DEF',
        driver: 'S. Williams',
        deliveriesDone: 28,
        deliveriesTotal: 35,
        boxesDone: 134,
        boxesTotal: 168,
        status: 'In Progress',
      },
      {
        routeId: 'route-d',
        routeName: 'Route D',
        description: 'W zones',
        vehicle: 'RS22 GHI',
        driver: 'T. O\'Brien',
        deliveriesDone: 41,
        deliveriesTotal: 56,
        boxesDone: 196,
        boxesTotal: 268,
        status: 'Exception',
        progressNote: '73% · 2 exceptions',
      },
      {
        routeId: 'route-e',
        routeName: 'Route E',
        description: 'N zones',
        vehicle: 'TU18 JKL',
        driver: 'M. Khan',
        deliveriesDone: 0,
        deliveriesTotal: 28,
        boxesDone: 0,
        boxesTotal: 138,
        status: 'Departed',
        progressNote: 'Departed 11:30',
      },
      {
        routeId: 'route-f',
        routeName: 'Route F',
        description: 'E zones',
        vehicle: 'VW21 MNO',
        driver: 'C. Davis',
        deliveriesDone: 0,
        deliveriesTotal: 0,
        boxesDone: 0,
        boxesTotal: 0,
        status: 'Pending',
        progressNote: 'Awaiting manifest',
      },
    ],
    openExceptions: [
      { orderId: 'ORD-4421', boxesSummary: '2 of 3', routeName: 'Route D' },
      { orderId: 'ORD-4398', boxesSummary: '1 of 2', routeName: 'Route D' },
      { orderId: 'ORD-4367', boxesSummary: '3 of 4', routeName: 'Route B' },
    ],
    awaitingGoods: [
      { orderId: 'ORD-4501', expectedBoxes: 4, receivedBoxes: 2 },
      { orderId: 'ORD-4498', expectedBoxes: 2, receivedBoxes: 2 },
      { orderId: 'ORD-4487', expectedBoxes: 6, receivedBoxes: 4 },
    ],
  },
  routeDrilldown: {
    'route-b': {
      routeName: 'Route B',
      vehicle: 'MN20 XYZ',
      driver: 'R. Ahmed',
      stats: {
        deliveriesDone: 31,
        deliveriesTotal: 48,
        boxesDone: 148,
        boxesTotal: 230,
        exceptionsCount: 1,
        lastActivity: '11:43',
        lastActivityPostcode: 'SE5 7AB',
      },
      stops: [
        { seq: 1, address: '14 Borough Market St', postcode: 'SE1 9AB', boxes: 3, status: 'Delivered', deliveryTime: '08:54', hasPod: true },
        { seq: 2, address: '88 Tooley Street', postcode: 'SE1 2TF', boxes: 1, status: 'Delivered', deliveryTime: '09:11', hasPod: true },
        { seq: 3, address: '21 Bermondsey St', postcode: 'SE1 3UH', boxes: 5, status: 'Delivered', deliveryTime: '09:28', hasPod: true },
        { seq: 6, address: '77 Denmark Hill', postcode: 'SE5 8RX', boxes: '2 of 3', status: 'Part Delivered', deliveryTime: '10:19', hasPod: true },
        { seq: 32, address: '19 New Cross Road', postcode: 'SE14 5DS', boxes: 3, status: 'Pending', hasPod: false },
        { seq: 33, address: '8 Lewisham High St', postcode: 'SE13 6EJ', boxes: 2, status: 'Pending', hasPod: false },
      ],
    },
  },
  ordersAwaitingGoods: [
    {
      orderId: 'ORD-4501',
      customer: 'B&Q Vauxhall',
      routeName: 'Route A',
      boxesReceived: 2,
      boxesExpected: 4,
      boxes: [
        { id: 'BOX-001', status: 'received', receivedAt: '09:14' },
        { id: 'BOX-002', status: 'received', receivedAt: '09:14' },
        { id: 'BOX-003', status: 'pending' },
        { id: 'BOX-004', status: 'pending' },
      ],
    },
    {
      orderId: 'ORD-4498',
      customer: 'Acme Supplies',
      routeName: 'Route A',
      boxesReceived: 2,
      boxesExpected: 2,
      boxes: [
        { id: 'BOX-DSP8820-001', status: 'received', receivedAt: '10:15' },
        { id: 'BOX-DSP8820-002', status: 'received', receivedAt: '10:15' },
      ],
    },
    {
      orderId: 'ORD-4487',
      customer: 'TechParts Ltd',
      routeName: 'Route B',
      boxesReceived: 4,
      boxesExpected: 6,
      boxes: [
        { id: 'BOX-001', status: 'received', receivedAt: '08:30' },
        { id: 'BOX-002', status: 'received', receivedAt: '08:30' },
        { id: 'BOX-003', status: 'received', receivedAt: '08:30' },
        { id: 'BOX-004', status: 'received', receivedAt: '08:30' },
        { id: 'BOX-005', status: 'pending' },
        { id: 'BOX-006', status: 'pending' },
      ],
    },
    {
      orderId: 'ORD-4477',
      customer: 'Metro Foods',
      routeName: 'Route D',
      boxesReceived: 0,
      boxesExpected: 5,
      boxes: [
        { id: 'BOX-001', status: 'pending' },
        { id: 'BOX-002', status: 'pending' },
        { id: 'BOX-003', status: 'pending' },
        { id: 'BOX-004', status: 'pending' },
        { id: 'BOX-005', status: 'pending' },
      ],
    },
  ],
  postcodeRules: [
    { pattern: 'SW8 1RT', level: 'full', routeId: 'route-a', routeName: 'Route A', effectiveFrom: '2026-01-01' },
    { pattern: 'SW8 1', level: 'sector', routeId: 'route-a', routeName: 'Route A', effectiveFrom: '2026-01-01' },
    { pattern: 'SW8', level: 'district', routeId: 'route-a', routeName: 'Route A', effectiveFrom: '2026-01-01' },
    { pattern: 'SE1', level: 'district', routeId: 'route-b', routeName: 'Route B', effectiveFrom: '2026-01-01' },
    { pattern: 'EC1', level: 'district', routeId: 'route-c', routeName: 'Route C', effectiveFrom: '2026-01-01' },
    { pattern: 'S', level: 'letter', routeId: 'route-a', routeName: 'Route A', effectiveFrom: '2024-01-01' },
  ],
  vehicles: [
    {
      id: 'vehicle-1',
      depotId: 'depot-1',
      registration: 'LK71 ABC',
      makeModel: 'Ford Transit SWB',
      capacity: '900kg / 6m³',
      motDue: 'Aug 2026',
      nextService: 'Jun 2026',
      status: 'Active',
    },
    {
      id: 'vehicle-2',
      depotId: 'depot-1',
      registration: 'MN20 XYZ',
      makeModel: 'Ford Transit LWB',
      capacity: '1100kg / 8m³',
      motDue: 'Sep 2026',
      nextService: 'Jul 2026',
      status: 'Active',
    },
    {
      id: 'vehicle-3',
      depotId: 'depot-1',
      registration: 'PQ19 DEF',
      makeModel: 'Mercedes Sprinter',
      capacity: '1200kg / 9m³',
      motDue: 'Nov 2026',
      nextService: 'Aug 2026',
      status: 'Active',
    },
    {
      id: 'vehicle-4',
      depotId: 'depot-1',
      registration: 'VW21 MNO',
      makeModel: 'Mercedes Sprinter LWB',
      capacity: '1300kg / 10m³',
      motDue: 'Apr 2026',
      nextService: 'Mar 2026',
      status: 'MOT Due Soon',
    },
  ],
  drivers: [
    {
      id: 'driver-1',
      depotId: 'depot-1',
      name: 'James Patel',
      licenceNo: 'PATEL901021JA9ML',
      expiry: 'Mar 2029',
      contact: '07700 900123',
      todaysRouteId: 'route-a',
      status: 'Active',
    },
    {
      id: 'driver-2',
      depotId: 'depot-1',
      name: 'Razia Ahmed',
      licenceNo: 'AHMED850514RA9ML',
      expiry: 'Nov 2027',
      contact: '07700 900456',
      todaysRouteId: 'route-b',
      status: 'Active',
    },
    {
      id: 'driver-3',
      depotId: 'depot-1',
      name: 'Sarah Williams',
      licenceNo: 'WILLI910308SW2ML',
      expiry: 'Jul 2028',
      contact: '07700 900789',
      todaysRouteId: 'route-c',
      status: 'Active',
    },
    {
      id: 'driver-4',
      depotId: 'depot-1',
      name: 'Thomas O\'Brien',
      licenceNo: 'OBRIE880712TO9ML',
      expiry: 'Feb 2027',
      contact: '07700 900012',
      todaysRouteId: 'route-d',
      status: 'Active',
    },
    {
      id: 'driver-5',
      depotId: 'depot-1',
      name: 'Anna Kowalski',
      licenceNo: 'KOWAL950617AK1ML',
      expiry: 'Dec 2029',
      contact: '07700 900901',
      status: 'Unavailable',
    },
  ],
  manifests: [
    {
      id: 'manifest-1',
      routeId: 'route-f',
      date: '2026-03-12',
      driverId: 'driver-6',
      vehicleId: 'vehicle-4',
      status: 'Draft',
      stops: [
        { orderId: 'ORD-4505', address: '14 Commercial Rd E1', boxes: 4, boxStatus: 'Ready' },
        { orderId: 'ORD-4507', address: '8 Whitechapel High St', boxes: 2, boxStatus: 'Ready' },
        { orderId: 'ORD-4511', address: '22 Bow Road E3', boxes: '3 of 5', boxStatus: 'Part — 2 missing' },
        { orderId: 'ORD-4515', address: '99 Isle of Dogs E14', boxes: '2 of 3', boxStatus: 'Part — 1 missing' },
      ],
    },
  ],
  users: [
    {
      id: 'user-1',
      name: 'Chris Admin',
      email: 'c.admin@deliverops.com',
      role: 'CENTRAL_ADMIN',
      lastLogin: 'Today 09:02',
      status: 'Active',
    },
    {
      id: 'user-2',
      name: 'Jane Smith',
      email: 'j.smith@depot-london.co.uk',
      role: 'DEPOT_MANAGER',
      depotId: 'depot-1',
      lastLogin: 'Today 08:15',
      status: 'Active',
    },
    {
      id: 'user-3',
      name: 'Mike Brown',
      email: 'm.brown@depot-mcr.co.uk',
      role: 'DEPOT_MANAGER',
      depotId: 'depot-2',
      lastLogin: 'Yesterday',
      status: 'Active',
    },
    {
      id: 'user-4',
      name: 'James Patel',
      email: 'j.patel@depot-london.co.uk',
      role: 'driver',
      depotId: 'depot-1',
      lastLogin: 'Today 07:58',
      status: 'Active',
    },
  ],
  auditEvents: [
    {
      timestamp: '12/03/26 11:32',
      userId: 'user-2',
      userName: 'Jane Smith',
      role: 'Depot Mgr',
      action: 'UPDATE',
      entityType: 'Postcode Rule',
      detail: 'SW8 1RT → Route A (eff. 13/03/26)',
    },
    {
      timestamp: '12/03/26 10:15',
      userId: 'user-2',
      userName: 'Jane Smith',
      role: 'Depot Mgr',
      action: 'CREATE',
      entityType: 'Manifest',
      detail: 'Route E confirmed — 28 stops, 138 boxes',
    },
    {
      timestamp: '12/03/26 09:44',
      userId: 'user-2',
      userName: 'Jane Smith',
      role: 'Depot Mgr',
      action: 'CREATE',
      entityType: 'Order',
      detail: 'ORD-4521 / DSP-8834 — SW8 1RT → Route A',
    },
    {
      timestamp: '11/03/26 16:02',
      userId: 'user-1',
      userName: 'Chris Admin',
      role: 'Central Admin',
      action: 'UPDATE',
      entityType: 'Postcode Rule',
      detail: 'SE14 5 moved: Route C → Route B (eff. 01/04/26)',
    },
    {
      timestamp: '09/03/26 09:05',
      userId: 'api-system',
      userName: 'API System',
      role: 'API',
      action: 'CREATE',
      entityType: 'Order',
      detail: 'ORD-4499 / DSP-8810 — N1 7GH → Route E (via API)',
    },
  ],
};
